name: canonizing-flaws
description: Register and protect emergent behaviors in the Canon of Flaws
version: "3.0.0"

triggers:
  - "/canonize"
  - "/canonise"  # British spelling

examples:
  - input: "/canonize"
    description: "Start flaw canonization interview"
  - input: "/canonize double-click-submit"
    description: "Protect the double-click submit animation"

inputs:
  - name: behavior_name
    type: string
    required: false
    description: "Name of the emergent behavior to protect"

outputs:
  - path: sigil-mark/soul-binder/canon-of-flaws.yaml
    description: Updated Canon of Flaws with new entry
