# Skill: Auditing Cohesion
# Purpose: Check visual consistency against fidelity ceiling and context
# Law: "Cohesion over technology"

version: "5.0.0"

skill: auditing_cohesion
purpose: |
  Verify visual properties match fidelity ceiling constraints and
  maintain cohesion with neighboring elements. The Mod Ghost Lesson:
  a flashy effect that breaks cohesion is worse than no effect.

trigger:
  - New component generation
  - Significant visual change
  - /garden command (runs all audits)
  - /garden --drift command (focuses on visual drift)

implementation:

  steps:
    1_identify_visual_properties:
      description: "Extract visual properties from generated component"
      properties:
        - shadows
        - border_radius
        - colors
        - typography
        - spacing
        - animation

    2_identify_context:
      description: "Find surrounding components"
      sources:
        - Parent component
        - Sibling components
        - Same-page components
        - Zone defaults

    3_compare_properties:
      description: "Check variance against thresholds"
      thresholds:
        shadow:
          same_container: 0
          adjacent_section: 1
        border_radius:
          same_container: 0
          adjacent_section: 4px
        color_temperature:
          same_container: match

    4_report_variance:
      description: "If significant, report with options"

output:

  format: |
    COHESION CHECK: {component_name}

    Variance detected:
    - {property}: {component_value} vs context {context_value}

    Options:
    1. MATCH CONTEXT - Adjust to {suggested_value}
    2. KEEP CURRENT - Intentional differentiation
    3. PROPOSE AMENDMENT - Change context standard

  examples:
    - variance: "shadow-lg vs shadow-none"
      suggestion: "Dashboard uses flat cards. Consider shadow-none or shadow-sm."

    - variance: "rounded-full vs rounded-md"
      suggestion: "Sibling cards use rounded-md. Consider matching."

agent_behavior:

  on_variance_detected:
    action: report
    block: false
    prompt: |
      This {component} uses {property}: {value}, but the surrounding
      context uses {context_value}.

      Shall I:
      1. Match context ({context_value})
      2. Keep current (intentional differentiation)
      3. Propose amendment (update context standard)

anti_patterns:
  - "Don't check in isolation"
  - "Don't enforce without context"
  - "Don't block on cohesion (report only)"

rationale: |
  The Mod Ghost Lesson: A modular component that's technically correct
  but visually inconsistent breaks the experience.

  Cohesion is about feel, not rules. Check the neighbors.

# =============================================================================
# FIDELITY CEILING CHECKS (S8-T1)
# =============================================================================

fidelity_audit:
  source: kernel/fidelity.yaml

  checks:
    animation:
      properties:
        - duration_ms  # Must be within min/max
        - easing       # Must be in allowed list
      severity: warning

    shadows:
      properties:
        - layer_count  # <= max_layers
        - blur_px      # <= max_blur_px
        - spread_px    # <= max_spread_px
      severity: warning

    borders:
      properties:
        - width_px     # <= max_width_px
        - radius_px    # In allowed_radii
      severity: warning

    typography:
      properties:
        - font_weight  # In allowed_weights
        - font_size    # >= 12px
      severity: warning

    colors:
      properties:
        - uses_tokens  # No raw hex
      severity: warning

# =============================================================================
# INTEGRATION
# =============================================================================

integration:
  garden_command:
    runs_with:
      - auditing_cohesion
      - simulating_interaction
    output: "Combined health report"

  garden_drift:
    focus: "Visual drift only"
    output: "Drift report"
