# Skill: Negotiating Integrity
# Purpose: Handle conflicts between user intent and constitution
# Law: "Never refuse outright. Always negotiate."

version: "5.0.0"

skill: negotiating_integrity
purpose: |
  Handle conflicts between user intent and constitution gracefully.
  Offer options, don't block. Capture justification for overrides.

trigger:
  - User request violates constitution
  - Data type doesn't match physics requirements
  - Fidelity ceiling exceeded
  - Workflow rule violated

implementation:

  protocol:
    1_detect_violation:
      description: "Identify which article is violated"
      sources:
        - constitution.yaml
        - fidelity.yaml
        - workflow.yaml

    2_assess_risk:
      description: "Determine violation severity"
      levels:
        - critical   # Security, data loss, financial
        - high       # User experience, accessibility
        - medium     # Consistency, best practice
        - low        # Preference, style

    3_present_options:
      description: "Offer COMPLY, BYPASS, or AMEND"

    4_capture_justification:
      description: "If BYPASS, log to governance"

output:

  format: |
    This request conflicts with the Constitution.

    VIOLATION: {violation_description}
    ARTICLE: {article_reference}
    RISK: {risk_level}

    OPTIONS:
    1. COMPLY - {compliant_alternative}
    2. BYPASS - Override with justification (will be logged)
    3. AMEND - Propose constitution change

    Which do you prefer?

  examples:
    - violation: "Using useOptimistic with Money type"
      article: "constitution.financial.forbidden[0]"
      risk: "critical"
      comply: "Use useSigilMutation with simulation flow"
      bypass: "Override with justification"
      amend: "Propose exception for demo accounts"

options:

  comply:
    description: "Use the compliant alternative"
    action: "Generate code with compliant pattern"
    logging: none

  bypass:
    description: "Override with justification"
    action: "Generate requested code with @sigil-override comment"
    logging: "Log to governance/justifications.log"
    format: |
      // @sigil-override: {rule_id}
      // Reason: {justification}
      // Author: {author}
      // Date: {date}

  amend:
    description: "Propose constitution change"
    action: "Create amendment proposal in governance/amendments/"
    logging: "Create amendment YAML"
    format: |
      # amendments/{date}-{rule_id}.yaml
      id: AMEND-{year}-{sequence}
      date: {date}
      proposer: {author}
      status: proposed
      article: {article}
      current_rule: {current}
      proposed_change: {proposed}
      justification: {justification}

justification_capture:

  prompt: |
    Override detected: {rule_id}

    Why is this override needed?
    (One sentence is sufficient. This helps future decisions.)

  log_format: |
    [{timestamp}] BYPASS
      File: {file_path}
      Article: {article}
      Violation: {violation}
      Justification: "{justification}"
      Override: @sigil-override: {rule_id}
      Author: {author}

  destination: "sigil-mark/governance/justifications.log"

anti_patterns:
  - "Never refuse outright"
  - "Never block without options"
  - "Never skip justification capture"

rationale: |
  One good reason > 15% silent mutiny.

  If we refuse outright, users disable the tool.
  If we capture justification, we learn and evolve.
  The constitution is law, but law can be amended.
