# Skill: Polishing Code
# Purpose: JIT standardization on demand
# Law: "Fix when asked, not on save"

version: "5.0.0"

skill: polishing_code
purpose: |
  Standardize code on demand, not automatically.
  Let humans debug with messy code. Polish when they ask.

trigger:
  - User runs /polish
  - Pre-commit hook
  - CI check

# =============================================================================
# KEY PRINCIPLE
# =============================================================================

principle: |
  NEVER AUTO-FIX ON SAVE.

  Messy code is debugging context. If code auto-cleans:
  - Developer loses state
  - Flow is broken
  - Trust is lost

  Let humans debug with messy code. Polish on demand.

# =============================================================================
# SEVERITY LEVELS
# =============================================================================

severity:
  error:
    description: "Must be fixed before commit"
    examples:
      - hitbox_too_small
      - focus_ring_missing
      - wrong_physics_for_financial
    exit_code: 1

  warning:
    description: "Should be fixed, but not blocking"
    examples:
      - animation_duration_exceeded
      - shadow_layers_exceeded
      - cohesion_mismatch
    exit_code: 0

  info:
    description: "Suggestion for improvement"
    examples:
      - could_use_design_token
      - optional_optimization
    exit_code: 0

# =============================================================================
# IMPLEMENTATION
# =============================================================================

implementation:

  triggers:
    manual:
      command: "/polish"
      behavior: "Scan, show diff, apply on approval"

    pre_commit:
      hook: ".husky/pre-commit"
      behavior: "Scan, fail if violations, suggest fix"

    ci:
      action: "sigil polish --check"
      behavior: "Scan, fail if violations, report"

  process:
    1_scan:
      description: "Find taste violations in file(s)"
      checks:
        - fidelity_ceiling
        - constitution_requirements
        - cohesion_rules
        - naming_conventions

    2_generate_fixes:
      description: "Create fix for each violation"
      output: "Unified diff format"

    3_present_diff:
      description: "Show before/after to user"
      grouping: "By file"

    4_apply:
      description: "Apply ONLY on explicit approval"
      confirmation: "Apply these changes? [y/N]"

violation_types:

  fidelity:
    - animation_duration_exceeded
    - shadow_layers_exceeded
    - gradient_stops_exceeded
    - border_radius_non_standard
    - font_size_too_small

  constitution:
    - wrong_physics_for_type
    - missing_simulation_flow
    - optimistic_on_financial
    - blocking_on_collaborative

  cohesion:
    - shadow_mismatch
    - radius_mismatch
    - color_temperature_mismatch

  conventions:
    - component_naming
    - file_naming
    - hook_naming
    - type_naming

output:

  diff_format: |
    --- a/{file_path}
    +++ b/{file_path}
    @@ -{old_line},{old_count} +{new_line},{new_count} @@
     {context}
    -{old_code}
    +{new_code}
     {context}

  summary_format: |
    POLISH REPORT

    Files scanned: {count}
    Violations found: {count}
    - Fidelity: {count}
    - Constitution: {count}
    - Cohesion: {count}
    - Conventions: {count}

    {diff_preview}

    Apply these changes? [y/N]

  check_format: |
    POLISH CHECK

    {violations_if_any}

    Run `sigil polish` to fix these issues.

commands:

  polish:
    description: "Scan and fix violations"
    flags:
      --diff: "Show diff without applying"
      --apply: "Apply without confirmation"
      --check: "Check only, exit non-zero if violations"
      --file: "Limit to specific file"

  examples:
    - command: "/polish"
      behavior: "Interactive fix flow"

    - command: "/polish --diff"
      behavior: "Show what would change"

    - command: "/polish --check"
      behavior: "CI mode, fail if violations"

pre_commit_hook: |
  #!/bin/bash
  # .husky/pre-commit

  # Run polish check
  npx sigil polish --check

  if [ $? -ne 0 ]; then
    echo ""
    echo "Sigil violations detected."
    echo "Run 'npx sigil polish' to fix."
    echo ""
    exit 1
  fi

anti_patterns:
  - "Never auto-fix on save"
  - "Never fix without showing diff"
  - "Never apply without confirmation"
  - "Never block debugging with auto-formatting"

rationale: |
  Engineers need to debug with messy code.
  border: 1px solid red; is a valid debugging technique.
  Auto-fix on save removes it before you can use it.

  Polish when asked. Not on keystroke.
