# Skill: Scanning Sanctuary
# Purpose: Find components via live grep (no cache)
# Law: "Filesystem is truth"

version: "5.0.0"

skill: scanning_sanctuary
purpose: |
  Find components by tier, zone, or data type using live filesystem search.
  Never use cached indexes. ripgrep on every lookup.

trigger:
  - Any component lookup
  - Finding Gold tier components
  - Finding components by zone
  - Finding components by data type

# =============================================================================
# JSDOC PRAGMA SPECIFICATION (S4-T1)
# =============================================================================

pragmas:

  sigil_tier:
    description: "Component quality and stability tier"
    syntax: "@sigil-tier {tier}"
    values:
      gold: "Production-ready, fully reviewed and tested"
      silver: "Stable, may need minor refinement"
      bronze: "Functional, needs review"
      draft: "Work in progress, not for production"
    example: |
      /**
       * @sigil-tier gold
       * ClaimButton - Critical financial action component
       */

  sigil_zone:
    description: "Semantic zone determining physics class"
    syntax: "@sigil-zone {zone}"
    values:
      critical: "Financial/health flows → server-tick physics"
      glass: "Marketing/exploration → local-first physics"
      machinery: "Admin/power-user → local-first (snappy) physics"
      standard: "Default → crdt physics"
    example: |
      /**
       * @sigil-tier gold
       * @sigil-zone critical
       * PaymentForm - Handles financial transactions
       */

  sigil_data_type:
    description: "Data type for physics resolution via constitution"
    syntax: "@sigil-data-type {type}"
    values:
      Money: "Financial amounts → server-tick"
      Health: "Health/status data → server-tick"
      Task: "Collaborative work items → crdt"
      Preference: "User settings → local-first"
      Filter: "UI state → local-first"
    example: |
      /**
       * @sigil-tier gold
       * @sigil-zone critical
       * @sigil-data-type Money
       * WithdrawButton - Handles withdrawal of funds
       */

# =============================================================================
# RIPGREP PATTERNS (S4-T2)
# =============================================================================

implementation:

  patterns:
    # Tier lookup
    by_tier: 'rg "@sigil-tier {tier}" -l --type ts --type tsx'
    by_tier_with_context: 'rg "@sigil-tier {tier}" -A 3 --type ts --type tsx'

    # Zone lookup
    by_zone: 'rg "@sigil-zone {zone}" -l --type ts --type tsx'
    by_zone_with_context: 'rg "@sigil-zone {zone}" -A 3 --type ts --type tsx'

    # Data type lookup
    by_data_type: 'rg "@sigil-data-type {type}" -l --type ts --type tsx'
    by_data_type_with_context: 'rg "@sigil-data-type {type}" -A 3 --type ts --type tsx'

    # Combined patterns
    gold_in_critical: 'rg "@sigil-tier gold" -l --type ts | xargs rg "@sigil-zone critical" -l'
    by_tier_and_zone: 'rg "@sigil-tier {tier}" -l --type ts | xargs rg "@sigil-zone {zone}" -l'
    all_pragmas: 'rg "@sigil-(tier|zone|data-type)" --type ts --type tsx'

  examples:
    - command: 'rg "@sigil-tier gold" -l --type ts'
      description: "Find all Gold tier components"
      expected: "List of file paths"

    - command: 'rg "@sigil-zone critical" -l --type ts'
      description: "Find all components in critical zone"
      expected: "List of file paths"

    - command: 'rg "@sigil-data-type Money" -l --type ts'
      description: "Find all components handling Money type"
      expected: "List of file paths"

    - command: 'rg "@sigil-tier gold" -A 5 --type ts'
      description: "Find Gold tier components with context"
      expected: "File content with surrounding lines"

    - command: 'rg "@sigil-tier gold" -l --type ts | xargs rg "@sigil-zone critical" -l'
      description: "Find Gold tier components in critical zone"
      expected: "Intersection of both criteria"

# =============================================================================
# PERFORMANCE
# =============================================================================

performance:
  target_ms: 50
  typical_codebase: "< 50ms for 10k files"
  large_codebase: "< 200ms for 100k files"
  fallback: "If slow, limit to specific directories with -g pattern"

  optimization_tips:
    - "Use -l for file paths only (faster)"
    - "Use --type ts to limit to TypeScript files"
    - "Use -g 'src/**' to limit search scope"
    - "Avoid . in pattern when possible"

# =============================================================================
# ANTI-PATTERNS
# =============================================================================

anti_patterns:
  - pattern: "sigil.map"
    reason: "Cached component lists become stale on branch switch"

  - pattern: ".sigil-cache"
    reason: "Any cache can hallucinate deleted components"

  - pattern: "prebuilt index"
    reason: "Git history doesn't update caches automatically"

  - pattern: "component registry JSON"
    reason: "JSON registries need manual sync with filesystem"

# =============================================================================
# RATIONALE
# =============================================================================

rationale: |
  Branch switch = stale cache = hallucination.
  ripgrep is fast enough. Use it on every lookup.
  The filesystem is the only truth.

  Why live grep:
  1. Branch switches don't update caches
  2. Uncommitted changes are invisible to cached indexes
  3. Deleted files still appear in stale caches
  4. ripgrep < 50ms is faster than cache lookup + validation

  The cost of cache invalidation bugs is higher than the cost of grep.
