# Skill: Simulating Interaction
# Purpose: Verify interaction timing meets physics requirements
# Law: "Feel is in the timing"

version: "5.0.0"

skill: simulating_interaction
purpose: |
  Verify interaction timing meets physics requirements.
  Click-to-feedback > 100ms = broken feel.

trigger:
  - Critical component generation
  - /craft --simulate command
  - Interactive component with physics requirements

implementation:

  measurements:
    click_to_feedback:
      target_ms: 100
      enforcement: error
      description: "Time from click to visual acknowledgment"
      test: "Button click shows immediate state change"

    keypress_to_action:
      target_ms: 50
      enforcement: warning
      description: "Time from keypress to visible response"
      test: "Enter key triggers visible action"

    hover_to_tooltip:
      target_ms: 200
      enforcement: warning
      description: "Time from hover to tooltip appearance"
      test: "Hover shows tooltip within threshold"

    scroll_to_render:
      target_ms: 16
      enforcement: warning
      description: "Frame budget for 60fps scrolling"
      test: "Scroll renders without jank"

  verification_methods:

    static_analysis:
      description: "Check code patterns for timing issues"
      patterns:
        - async_without_pending: "Async handler without isPending check"
        - missing_optimistic: "Server action without optimistic update"
        - blocking_ui: "await without loading state"

    simulation:
      description: "Trace interaction flow timing"
      steps:
        - User action (click, keypress)
        - State change triggered
        - Visual feedback rendered
        - Server response (if applicable)
        - Final state rendered

output:

  format: |
    INTERACTION SIMULATION: {component_name}

    Timing Analysis:
    - click_to_feedback: {measured}ms (target: < 100ms) {status}
    - keypress_to_action: {measured}ms (target: < 50ms) {status}

    {issues_if_any}

  pass_example: |
    INTERACTION SIMULATION: ClaimButton

    Timing Analysis:
    - click_to_feedback: 50ms (target: < 100ms) PASS
    - Simulation preview: 200ms PASS
    - Confirmation flow: immediate PASS

    All timing requirements met.

  fail_example: |
    INTERACTION SIMULATION: ClaimButton

    Timing Analysis:
    - click_to_feedback: 250ms (target: < 100ms) FAIL

    Issue: No immediate feedback on click.

    Suggestion: Add optimistic state change before server call.

    Example:
    ```tsx
    const [isPending, setIsPending] = useState(false);

    const handleClick = async () => {
      setIsPending(true);  // Immediate feedback
      await claim();
      setIsPending(false);
    };
    ```

physics_timing:

  server_tick:
    simulation_start: immediate
    preview_display: < 200ms
    confirmation_prompt: immediate
    commit_feedback: immediate (pending state)
    completion: < 1200ms total

  crdt:
    local_update: immediate
    sync_indication: < 50ms
    conflict_resolution: background
    completion: < 300ms perceived

  local_first:
    state_change: immediate
    visual_update: < 50ms
    persist: background
    completion: < 50ms perceived

anti_patterns:
  - "await without loading state"
  - "Server round-trip before feedback"
  - "No pending indication"
  - "Blocking UI during async"

rationale: |
  100ms is the threshold where interaction feels instant.
  Beyond that, users notice lag and lose confidence.

  For server-tick physics, we can't make the action faster,
  but we CAN give immediate feedback that action is in progress.

# =============================================================================
# TIMING VERIFICATION (S8-T2)
# =============================================================================

timing_thresholds:
  click_to_feedback:
    target_ms: 100
    enforcement: error
    description: "Time from click to visual acknowledgment"
    violation_message: "Click feedback exceeds 100ms threshold"
    fix_suggestion: "Add immediate state change (isPending, disabled) before async"

  keypress_to_action:
    target_ms: 50
    enforcement: warning
    description: "Time from keypress to visible response"
    violation_message: "Keypress response exceeds 50ms threshold"
    fix_suggestion: "Ensure keyboard handlers are synchronous for immediate feedback"

  hover_to_tooltip:
    target_ms: 200
    enforcement: warning
    description: "Time from hover to tooltip appearance"
    violation_message: "Tooltip appears after 200ms delay"
    fix_suggestion: "Use immediate tooltip or add delay prop < 200ms"

  scroll_to_render:
    target_ms: 16
    enforcement: warning
    description: "Frame budget for 60fps scrolling"
    violation_message: "Scroll causes frame drops"
    fix_suggestion: "Use virtualization or reduce render complexity"

# =============================================================================
# INTEGRATION
# =============================================================================

integration:
  garden_command:
    runs_with:
      - auditing_cohesion
      - simulating_interaction
    output: "Combined health report"

  craft_simulate:
    runs_on: "--simulate flag"
    output: "Timing analysis for component"
