# Sigil v3.0 Configuration
# "Truth is Core. Experience is Lens. Layouts ARE Zones."

sigil: "3.0.0"
codename: "Living Engine"

# ═══════════════════════════════════════════════════════════════════════════════
# PROJECT METADATA
# ═══════════════════════════════════════════════════════════════════════════════

project:
  name: "Sigil Framework"

# ═══════════════════════════════════════════════════════════════════════════════
# v2.0 ZONES
# Layout-based zone configuration
# Zones are now declared via Layout primitives, not file paths
# ═══════════════════════════════════════════════════════════════════════════════

zones:
  # CriticalZone — High-stakes financial/destructive actions
  critical:
    layout: CriticalZone
    timeAuthority: server-tick
    lens: strict              # Forces StrictLens when financial=true
    constraints:
      optimistic_ui: forbidden
      loading_spinners: warn
      animations: warn
    # Persona-specific overrides for this zone
    persona_overrides:
      newcomer:
        lens: guided          # Newcomers get guided lens even in critical zone
        help: always
        density: low
        motion: reassuring
      power_user:
        lens: strict          # Power users keep strict lens
        help: on_demand
        density: medium       # Slightly less dense in critical zone
        motion: deliberate
      accessibility:
        lens: a11y
        help: always
        density: low
        motion: reduced

  # MachineryLayout — Keyboard-driven admin interfaces
  admin:
    layout: MachineryLayout
    timeAuthority: optimistic
    lens: user-preference     # Respects user's lens choice
    constraints:
      raw_physics: allowed
    persona_overrides:
      newcomer:
        lens: guided
        help: always
        density: medium
      power_user:
        lens: default         # Power users use default in admin (faster)
        help: never
        density: high

  # GlassLayout — Hover-driven marketing/showcase
  marketing:
    layout: GlassLayout
    timeAuthority: optimistic
    lens: user-preference
    constraints: {}           # No constraints for marketing
    persona_overrides:
      power_user:
        density: high         # Power users see more in marketing
        help: never
      newcomer:
        density: low
        help: contextual
        motion: warm

  # Default zone (no layout wrapper)
  default:
    layout: null
    timeAuthority: optimistic
    lens: default
    constraints: {}
    persona_overrides: {}

# ═══════════════════════════════════════════════════════════════════════════════
# LENS CONFIGURATION
# Which lenses are available and their classifications
# ═══════════════════════════════════════════════════════════════════════════════

lenses:
  # Built-in lenses
  DefaultLens:
    classification: cosmetic
    minTouchTarget: 44px
    animations: true
    description: "Standard UI with animations and 44px touch targets"

  StrictLens:
    classification: cosmetic
    minTouchTarget: 48px
    animations: false
    description: "High-contrast, no animations, for high-stakes actions"
    zones:
      - critical              # Auto-selected in critical+financial zones

  A11yLens:
    classification: cosmetic
    minTouchTarget: 56px
    animations: false
    wcag: AAA
    description: "WCAG AAA compliant, 56px targets, bold focus rings"

# ═══════════════════════════════════════════════════════════════════════════════
# v3.0 TERMINOLOGY NOTE
# - "Persona" = User archetype (power_user, newcomer, mobile, accessibility)
# - "Lens" = UI rendering variant (DefaultLens, StrictLens, A11yLens)
# - Zone detection is Layout-based (CriticalZone, MachineryLayout, GlassLayout)
# - Path-based zone detection was REMOVED in v2.0
# ═══════════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════════
# SANDBOX FILES (managed by /sandbox command)
# ═══════════════════════════════════════════════════════════════════════════════

sandbox: []

# ═══════════════════════════════════════════════════════════════════════════════
# REFINEMENT (optional)
# ═══════════════════════════════════════════════════════════════════════════════

refinement:
  sources:
    - vercel_preview_comments
    - github_pr_comments
    - linear_issue_comments
  auto_commit: true
  commit_prefix: "refine"
