# Sigil v10.1 Configuration
# "The codebase is the dataset. Usage is the authority."

sigil: "10.1.0"
codename: "Usage Reality"

# ===============================================================================
# PROJECT METADATA
# ===============================================================================

project:
  name: "Sigil Framework"

# ===============================================================================
# v4.1 ZONES
# Layout-based zone configuration with physics and persona overrides
# Zones are declared via Layout primitives, not file paths
# ===============================================================================

zones:
  # CriticalZone - High-stakes financial/destructive actions
  critical:
    layout: CriticalZone
    timeAuthority: server-tick
    lens: strict              # Forces StrictLens when financial=true
    motion: deliberate        # Base motion for critical zone

    # Default physics for this zone
    default_physics:
      sync: pessimistic       # Server owns clock
      timing: deliberate      # 800ms default
      motion: deliberate

    constraints:
      optimistic_ui: forbidden
      loading_spinners: warn
      animations: warn

    # Persona-specific overrides for this zone
    persona_overrides:
      newcomer:
        lens: guided          # Newcomers get guided lens even in critical zone
        help: always
        density: low
        motion: reassuring    # Slower, more reassuring for newcomers
        timing: reassuring    # 1200ms
        show_help: true
      power_user:
        lens: strict          # Power users keep strict lens
        help: on_demand
        density: medium       # Slightly less dense in critical zone
        motion: deliberate    # Standard deliberate motion
        timing: deliberate    # 800ms
        show_help: false
      accessibility:
        lens: a11y
        help: always
        density: low
        motion: reduced       # No/minimal motion

  # MachineryLayout - Keyboard-driven admin interfaces
  admin:
    layout: MachineryLayout
    timeAuthority: optimistic
    lens: user-preference     # Respects user's lens choice
    motion: snappy            # Base motion for admin zone

    # Default physics for this zone
    default_physics:
      sync: optimistic        # Client owns clock
      timing: snappy          # 150ms default
      motion: snappy

    constraints:
      raw_physics: allowed

    persona_overrides:
      newcomer:
        lens: guided
        help: always
        density: medium
        motion: warm          # Slightly slower for newcomers
        timing: warm          # 300ms
        show_help: true
      power_user:
        lens: default         # Power users use default in admin (faster)
        help: never
        density: high
        motion: instant       # Instant for power users
        timing: instant       # 0ms
        show_help: false

  # GlassLayout - Hover-driven marketing/showcase
  marketing:
    layout: GlassLayout
    timeAuthority: optimistic
    lens: user-preference
    motion: warm              # Base motion for marketing zone

    # Default physics for this zone
    default_physics:
      sync: optimistic        # Client owns clock
      timing: warm            # 300ms default
      motion: warm

    constraints: {}           # No constraints for marketing

    persona_overrides:
      power_user:
        density: high         # Power users see more in marketing
        help: never
        motion: snappy        # Faster for power users
        timing: snappy        # 150ms
        show_help: false
      newcomer:
        density: low
        help: contextual
        motion: warm          # Standard warm motion
        timing: warm          # 300ms
        show_help: true

  # Default zone (no layout wrapper)
  default:
    layout: null
    timeAuthority: optimistic
    lens: default
    motion: warm              # Base motion for default zone

    # Default physics for this zone
    default_physics:
      sync: optimistic
      timing: warm
      motion: warm

    constraints: {}
    persona_overrides: {}

# ===============================================================================
# LENS CONFIGURATION
# Which lenses are available and their classifications
# ===============================================================================

lenses:
  # Built-in lenses
  DefaultLens:
    classification: cosmetic
    minTouchTarget: 44px
    animations: true
    description: "Standard UI with animations and 44px touch targets"

  StrictLens:
    classification: cosmetic
    minTouchTarget: 48px
    animations: false
    description: "High-contrast, no animations, for high-stakes actions"
    zones:
      - critical              # Auto-selected in critical+financial zones

  A11yLens:
    classification: cosmetic
    minTouchTarget: 56px
    animations: false
    wcag: AAA
    description: "WCAG AAA compliant, 56px targets, bold focus rings"

# ===============================================================================
# v4.1 PHYSICS TIMING
# Motion name -> timing mapping (see physics.yaml for full definitions)
# ===============================================================================

physics:
  motion_timings:
    instant: 0
    snappy: 150
    warm: 300
    deliberate: 800
    reassuring: 1200
    celebratory: 1200
    reduced: 0

  motion_easings:
    instant: "linear"
    snappy: "ease-out"
    warm: "ease-in-out"
    deliberate: "ease-out"
    reassuring: "ease-in-out"
    celebratory: "cubic-bezier(0.34, 1.56, 0.64, 1)"
    reduced: "linear"

# ===============================================================================
# v4.1 TERMINOLOGY NOTE
# - "Persona" = User archetype (power_user, newcomer, mobile, accessibility)
# - "Lens" = UI rendering variant (DefaultLens, StrictLens, A11yLens)
# - Zone detection is Layout-based (CriticalZone, MachineryLayout, GlassLayout)
# - Path-based zone detection was REMOVED in v2.0
# ===============================================================================

# ===============================================================================
# SANDBOX FILES (managed by /sandbox command)
# ===============================================================================

sandbox: []

# ===============================================================================
# REFINEMENT (optional)
# ===============================================================================

refinement:
  sources:
    - vercel_preview_comments
    - github_pr_comments
    - linear_issue_comments
  auto_commit: true
  commit_prefix: "refine"
