# Sigil v1.2.4 Configuration
# "See the diff. Feel the result. Learn by doing."

sigil: "1.2.4"

# ═══════════════════════════════════════════════════════════════════════════════
# PROJECT METADATA
# ═══════════════════════════════════════════════════════════════════════════════

project:
  name: "Sigil Framework"

# ═══════════════════════════════════════════════════════════════════════════════
# RECIPES
# Which recipe set to use by default
# Options: decisive | machinery | glass
# ═══════════════════════════════════════════════════════════════════════════════

recipes: machinery

# ═══════════════════════════════════════════════════════════════════════════════
# COMPONENT DISCOVERY
# Where to find components that should use recipes
# ═══════════════════════════════════════════════════════════════════════════════

component_paths:
  - "components/**"
  - "src/components/**"
  - "app/components/**"
  - "packages/*/src/**"
  - "src/features/**/components/**"

# ═══════════════════════════════════════════════════════════════════════════════
# SYNC STRATEGY (optional)
# How UI syncs with server
# Options: client_authoritative | server_authoritative | server_tick
# ═══════════════════════════════════════════════════════════════════════════════

# sync: client_authoritative

# ═══════════════════════════════════════════════════════════════════════════════
# TICK DURATION (optional)
# For server_tick sync, how long to wait for confirmation
# ═══════════════════════════════════════════════════════════════════════════════

# tick: 600ms

# ═══════════════════════════════════════════════════════════════════════════════
# CONSTRAINTS (optional)
# Physics behaviors that are forbidden in this scope
# ═══════════════════════════════════════════════════════════════════════════════

# constraints:
#   optimistic_ui: forbidden
#   loading_spinners: forbidden

# ═══════════════════════════════════════════════════════════════════════════════
# SANDBOX FILES (managed by /sandbox command)
# Files where raw physics are allowed for experimentation
# ═══════════════════════════════════════════════════════════════════════════════

sandbox: []

# ═══════════════════════════════════════════════════════════════════════════════
# REFINEMENT (optional)
# PR-native feedback configuration
# ═══════════════════════════════════════════════════════════════════════════════

refinement:
  sources:
    - vercel_preview_comments
    - github_pr_comments
    - linear_issue_comments
  auto_commit: true
  commit_prefix: "refine"
