# Sigil v3.0 — Vibe Checks
# Micro-surveys for qualitative feedback + Behavioral signals for observation
#
# Philosophy: "Ask at the moment of emotion, not after it's gone."
#
# Two modes:
# 1. Triggers: Explicit surveys shown to users
# 2. Behavioral Signals: Passive observation patterns for UX insights
#
# Keep surveys short (1 question), non-intrusive, and respectful of cooldowns.
# Behavioral signals are passive — they observe, never interrupt.

version: "3.0.0"

triggers:
  # ==========================================================================
  # CRITICAL ZONE TRIGGERS
  # ==========================================================================

  - id: strategy_change
    name: Strategy Change Feedback
    trigger: action_completed
    trigger_event: strategy_updated
    question: "How confident do you feel about this strategy change?"
    type: scale
    options:
      - value: 1
        label: "Very uncertain"
      - value: 2
        label: "Somewhat uncertain"
      - value: 3
        label: "Neutral"
      - value: 4
        label: "Somewhat confident"
      - value: 5
        label: "Very confident"
    cooldown_days: 3
    zones: ["critical", "checkout"]
    priority: 10

  - id: first_deposit
    name: First Deposit Experience
    trigger: first_time
    trigger_event: deposit_completed
    question: "How was your first deposit experience?"
    type: emoji
    options:
      - value: 1
        label: "Frustrating"
        emoji: "😤"
      - value: 2
        label: "Confusing"
        emoji: "😕"
      - value: 3
        label: "Okay"
        emoji: "😐"
      - value: 4
        label: "Good"
        emoji: "🙂"
      - value: 5
        label: "Great"
        emoji: "😊"
    cooldown_days: 30
    zones: ["critical"]
    priority: 20

  - id: first_withdraw
    name: First Withdrawal Experience
    trigger: first_time
    trigger_event: withdraw_completed
    question: "How was your first withdrawal experience?"
    type: emoji
    options:
      - value: 1
        label: "Frustrating"
        emoji: "😤"
      - value: 2
        label: "Confusing"
        emoji: "😕"
      - value: 3
        label: "Okay"
        emoji: "😐"
      - value: 4
        label: "Good"
        emoji: "🙂"
      - value: 5
        label: "Great"
        emoji: "😊"
    cooldown_days: 30
    zones: ["critical"]
    priority: 20

  # ==========================================================================
  # ERROR RECOVERY TRIGGERS
  # ==========================================================================

  - id: transaction_failed
    name: Transaction Failed Recovery
    trigger: error_occurred
    trigger_event: transaction_error
    question: "Did you understand what went wrong?"
    type: choice
    options:
      - value: "yes"
        label: "Yes, it was clear"
      - value: "somewhat"
        label: "Somewhat, but confused"
      - value: "no"
        label: "No, I have no idea"
    cooldown_days: 7
    zones: ["critical"]
    priority: 15

  # ==========================================================================
  # DISCOVERY TRIGGERS
  # ==========================================================================

  - id: card_expanded
    name: Card Discovery Feedback
    trigger: action_completed
    trigger_event: card_expanded
    question: "Was this information helpful?"
    type: choice
    options:
      - value: "very"
        label: "Very helpful"
      - value: "somewhat"
        label: "Somewhat helpful"
      - value: "not"
        label: "Not helpful"
    cooldown_days: 14
    zones: ["marketing", "landing"]
    priority: 5

  # ==========================================================================
  # ONBOARDING TRIGGERS
  # ==========================================================================

  - id: onboarding_completed
    name: Onboarding Completion
    trigger: action_completed
    trigger_event: onboarding_done
    question: "How prepared do you feel to use the platform?"
    type: scale
    options:
      - value: 1
        label: "Not at all"
      - value: 2
        label: "A little"
      - value: 3
        label: "Moderately"
      - value: 4
        label: "Quite prepared"
      - value: 5
        label: "Very prepared"
    cooldown_days: 90
    zones: ["onboarding", "welcome"]
    priority: 25

# ==========================================================================
# FEEDBACK CONFIGURATION
# ==========================================================================

feedback:
  destination: console
  include_context: true
  anonymize: true

# ==========================================================================
# DISPLAY CONFIGURATION
# ==========================================================================

display:
  position: bottom-right
  delay_ms: 2000
  auto_dismiss_ms: 0
  show_dismiss: true
  theme: system

# ==========================================================================
# RATE LIMITS
# ==========================================================================

limits:
  max_per_session: 2
  max_per_day: 3
  min_interval_minutes: 30

# ==========================================================================
# BEHAVIORAL SIGNALS (v3.0)
# ==========================================================================
# Passive observation patterns for UX insights.
# These DON'T interrupt the user — they observe and record.
#
# Philosophy: "Observe behavior, don't survey it. Users show us more than they tell us."

behavioral_signals:
  # --------------------------------------------------------------------------
  # INFORMATION SEEKING PATTERNS
  # --------------------------------------------------------------------------

  - id: information_seeking
    name: Information Seeking
    description: "User is looking for more information before acting"
    triggers:
      - event: tooltip_hover
        duration_ms: 2000
      - event: help_icon_click
      - event: faq_expand
      - event: terms_scroll
    insight: "User wants more context before committing"
    recommendation: "Consider showing more upfront information or simplifying the decision"
    zones: ["critical", "onboarding"]
    severity: info
    enabled: true

  - id: confirmation_friction
    name: Confirmation Friction
    description: "User hesitates at confirmation dialogs"
    triggers:
      - event: confirmation_dialog_open
        idle_time_ms: 5000
      - event: confirmation_cancel
        within_ms: 3000
    insight: "User is uncertain about the action they're about to take"
    recommendation: "Review confirmation copy for clarity, ensure fees/impact are visible"
    zones: ["critical"]
    severity: warning
    enabled: true

  # --------------------------------------------------------------------------
  # FRUSTRATION PATTERNS
  # --------------------------------------------------------------------------

  - id: rage_clicking
    name: Rage Clicking
    description: "User clicks repeatedly on same element (frustration indicator)"
    triggers:
      - event: element_click
        count_threshold: 3
        within_ms: 2000
    insight: "User expects something to happen that isn't happening"
    recommendation: "Check if element is disabled without clear indication, or if loading state is unclear"
    zones: []  # All zones
    severity: high
    enabled: true

  - id: back_button_loop
    name: Back Button Loop
    description: "User navigates back multiple times quickly"
    triggers:
      - event: navigation_back
        count_threshold: 2
        within_ms: 5000
    insight: "User may be lost or trying to find something"
    recommendation: "Review navigation flow, consider adding breadcrumbs"
    zones: []  # All zones
    severity: warning
    enabled: true

  - id: form_abandonment
    name: Form Abandonment
    description: "User starts but doesn't complete a form"
    triggers:
      - event: form_field_focus
        followed_by: navigation_away
        without: form_submit
    insight: "Form may be too complex or asking for unexpected information"
    recommendation: "Review form length, field labels, and required vs optional fields"
    zones: ["critical", "onboarding"]
    severity: warning
    enabled: true

  # --------------------------------------------------------------------------
  # TRUST PATTERNS
  # --------------------------------------------------------------------------

  - id: security_checking
    name: Security Checking
    description: "User is verifying security indicators"
    triggers:
      - event: address_bar_focus
      - event: ssl_indicator_hover
      - event: security_badge_click
    insight: "User is cautious about security (good sign of awareness)"
    recommendation: "Ensure security indicators are prominent and trustworthy"
    zones: ["critical"]
    severity: info
    enabled: true

  - id: price_comparison
    name: Price Comparison
    description: "User is comparing prices or fees"
    triggers:
      - event: fee_tooltip_hover
        duration_ms: 3000
      - event: price_breakdown_expand
    insight: "User is price-sensitive or wants to understand costs"
    recommendation: "Consider more transparent fee disclosure or competitive messaging"
    zones: ["critical"]
    severity: info
    enabled: true

  # --------------------------------------------------------------------------
  # ENGAGEMENT PATTERNS
  # --------------------------------------------------------------------------

  - id: content_skimming
    name: Content Skimming
    description: "User scrolls quickly past content"
    triggers:
      - event: scroll
        velocity: fast
        content_visibility_ms: 500
    insight: "Content may not be engaging or user is looking for something specific"
    recommendation: "Review content hierarchy, add clear section headers"
    zones: ["marketing", "landing"]
    severity: info
    enabled: true

  - id: deep_engagement
    name: Deep Engagement
    description: "User spends significant time on content"
    triggers:
      - event: content_visible
        duration_ms: 30000
      - event: scroll
        velocity: slow
    insight: "User is highly engaged with this content"
    recommendation: "This content resonates — consider what makes it effective"
    zones: ["marketing", "landing"]
    severity: positive
    enabled: true
