name: graduating-features
description: Graduate a feature from proving to the Living Canon
version: "3.0.0"

triggers:
  - "/graduate"

examples:
  - input: "/graduate token-swap"
    description: "Graduate token-swap feature after proving"
  - input: "/graduate PROVE-2026-001"
    description: "Graduate feature by ID"

inputs:
  - name: feature
    type: string
    required: true
    description: Feature name or ID to graduate

outputs:
  - path: sigil-mark/canon/graduated/{feature}.yaml
    description: Graduated feature record in Living Canon
