name: reality-engine
description: Design governance system protecting intended and emergent product soul
version: "1.0.0"

triggers:
  - "soul check"
  - "flaw check"
  - "lens validate"
  - "grit check"
  - "consult"
  - "prove"
  - "graduate"

outputs:
  - "Flaw violation reports"
  - "Lens validation results"
  - "Grit analysis"
  - "Consultation facilitation"
  - "Proving Grounds monitoring"

dependencies:
  files:
    - "reality-engine/soul-binder/canon-of-flaws.yaml"
    - "reality-engine/soul-binder/immutable-values.yaml"
    - "reality-engine/soul-binder/visual-soul.yaml"
    - "reality-engine/lens-array/lenses.yaml"
    - "reality-engine/taste-owners.yaml"
