name: monitoring-features
description: Update monitor status for proving features
version: "3.0.0"

triggers: []  # Internal skill, not user-invoked

examples:
  - input: "Update tx_success_rate for token-swap to 99.5%"
    description: "Update a specific monitor value"

inputs:
  - name: feature_id
    type: string
    required: true
    description: Feature ID to update

  - name: monitor_id
    type: string
    required: true
    description: Monitor ID to update

  - name: value
    type: string
    required: true
    description: New monitor value

outputs: []  # Updates proving record in place

internal: true
