#!/bin/bash
#
# PR Screenshot Attachment
#
# Attaches screenshots to the current PR description.
#
# Usage:
#   ./pr-attach.sh <snapshot-dir> [--flow <flow-name>]
#   ./pr-attach.sh grimoires/sigil/snapshots/2026-01-19/
#   ./pr-attach.sh grimoires/sigil/snapshots/flows/claim/
#
# Requires:
#   - gh CLI authenticated
#   - Active PR on current branch
#
# Output:
#   Updates PR description with visual changes section

set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════

SNAPSHOT_DIR="${1:-}"
FLOW_NAME=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --flow)
      FLOW_NAME="$2"
      shift 2
      ;;
    *)
      if [[ -z "$SNAPSHOT_DIR" ]]; then
        SNAPSHOT_DIR="$1"
      fi
      shift
      ;;
  esac
done

if [[ -z "$SNAPSHOT_DIR" ]]; then
  echo "Usage: $0 <snapshot-dir> [--flow <flow-name>]" >&2
  exit 1
fi

if [[ ! -d "$SNAPSHOT_DIR" ]]; then
  echo "ERROR: Directory not found: $SNAPSHOT_DIR" >&2
  exit 1
fi

# ═══════════════════════════════════════════════════════════════════════════
# Check Prerequisites
# ═══════════════════════════════════════════════════════════════════════════

if ! command -v gh &> /dev/null; then
  echo "ERROR: gh CLI not found. Install: https://cli.github.com" >&2
  exit 1
fi

# Check for active PR
PR_NUMBER=$(gh pr view --json number -q '.number' 2>/dev/null || echo "")
if [[ -z "$PR_NUMBER" ]]; then
  echo "ERROR: No active PR found for current branch" >&2
  echo "Create a PR first with: gh pr create" >&2
  exit 1
fi

echo "Attaching screenshots to PR #$PR_NUMBER..."

# ═══════════════════════════════════════════════════════════════════════════
# Generate Markdown Section
# ═══════════════════════════════════════════════════════════════════════════

generate_visual_section() {
  local dir="$1"
  local flow="$2"

  echo "## 📸 Visual Changes"
  echo ""

  # Check for before/after pair
  local before_img=$(find "$dir" -name "*-before.png" -type f | head -1)
  local after_img=$(find "$dir" -name "*-after.png" -type f | head -1)

  if [[ -n "$before_img" && -n "$after_img" ]]; then
    echo "### Before / After"
    echo ""
    echo "| Before | After |"
    echo "|--------|-------|"
    echo "| ![before]($before_img) | ![after]($after_img) |"
    echo ""
  fi

  # List all screenshots
  local screenshots
  screenshots=$(find "$dir" -name "*.png" -type f | sort)

  if [[ -n "$screenshots" ]]; then
    echo "### Screenshots"
    echo ""

    if [[ -n "$flow" ]]; then
      echo "**Flow:** \`$flow\`"
      echo ""
    fi

    echo "$screenshots" | while read -r img; do
      local name=$(basename "$img" .png)
      echo "#### $name"
      echo ""
      echo "![${name}]($img)"
      echo ""
    done
  fi

  # Link to report if exists
  local report=$(find "$dir" -name "report.md" -type f | head -1)
  if [[ -n "$report" ]]; then
    echo "### Flow Report"
    echo ""
    echo "See [$report]($report) for full execution details."
    echo ""
  fi

  echo "---"
  echo ""
  echo "_Generated by Sigil Web3 Testing_"
}

# ═══════════════════════════════════════════════════════════════════════════
# Update PR Description
# ═══════════════════════════════════════════════════════════════════════════

# Get current PR body
CURRENT_BODY=$(gh pr view --json body -q '.body')

# Check if visual section already exists
if echo "$CURRENT_BODY" | grep -q "## 📸 Visual Changes"; then
  echo "Visual section already exists. Updating..."
  # Remove old section (everything from "## 📸 Visual Changes" to next "---" or end)
  NEW_BODY=$(echo "$CURRENT_BODY" | sed '/## 📸 Visual Changes/,/^---$/d')
else
  NEW_BODY="$CURRENT_BODY"
fi

# Generate new visual section
VISUAL_SECTION=$(generate_visual_section "$SNAPSHOT_DIR" "$FLOW_NAME")

# Append visual section
UPDATED_BODY="${NEW_BODY}

${VISUAL_SECTION}"

# Update PR
gh pr edit "$PR_NUMBER" --body "$UPDATED_BODY"

echo "✓ PR #$PR_NUMBER updated with visual changes"
echo ""
echo "View PR: $(gh pr view --json url -q '.url')"
