name: mapping-zones
description: Configure path-based design zones with physics and budgets
version: "1.0.0"
command: /map

role: "Zone Architect"
role_description: "Maps file paths to zones with physics, material, and budget settings"

outputs:
  - sigil-mark/resonance/zones.yaml (updated)

prerequisites:
  - sigil_mark_exists
  - essence_yaml_exists

triggers:
  - /map
  - /map --add
  - /map --paths
