name: observing-users
description: Capture and analyze user feedback using Level 3 diagnostic framework
version: 1.0.0
triggers:
  - /observe
  - user feedback
  - user research
  - mom test
  - diagnostic
files:
  - SKILL.md
dependencies:
  - crafting-physics  # For /craft integration
  - synthesizing-taste  # For pattern detection
