# Reality Engine Configuration
# This file configures the Reality Engine for your project

version: "1.0.0"

# Project identification
project:
  name: "Your Project Name"
  type: "game"  # game | saas | creative-tool | community-platform
  
# Feature flags
features:
  soul_binder:
    enabled: true
    canon_of_flaws: true
    grit_validation: true
  
  lens_array:
    enabled: true
    fixed_mode_validation: true
    resolution: "800x600"
  
  consultation_chamber:
    enabled: true
    concept_blog_duration_days: 7
    auto_lock_after_decision: true
  
  proving_grounds:
    enabled: true
    minimum_days: 7
    auto_graduate: false  # Require manual approval

# Paths
paths:
  soul_binder: "reality-engine/soul-binder"
  lens_array: "reality-engine/lens-array"
  consultation_chamber: "reality-engine/consultation-chamber"
  proving_grounds: "reality-engine/proving-grounds"
  canon: "reality-engine/canon"
  taste_owners: "reality-engine/taste-owners.yaml"

# Integration
integrations:
  # CI/CD
  ci:
    enabled: true
    block_on_flaw_violation: true
    block_on_fixed_mode_failure: true
    warn_on_grit_failure: true
  
  # Slack/Discord notifications
  notifications:
    channel: "#design-governance"
    on_flaw_violation: true
    on_consultation_started: true
    on_proving_complete: true
  
  # Sentiment sources for Consultation Chamber
  sentiment_sources:
    - type: "reddit"
      subreddit: "yourproject"
    - type: "discord"
      channel_id: "123456789"

# Thresholds
thresholds:
  # Canon of Flaws
  flaw_canonization:
    minimum_usage_percent: 5
    minimum_user_attachment: "high"
  
  # Grit validation
  grit:
    edge_roughness_min: 0.3
    color_band_visibility_min: 0.5
    texture_noise_min: 0.2
  
  # Proving Grounds
  proving:
    xp_rate_cap: 100000  # per hour
    inflation_rate_max_daily: 2.0  # percent
    exploit_severity_block: "P1"
