# Sigil Workflow Engine
# Process is soul. Wrong method = wrong product.
# Based on Linear Method principles

version: "5.0.0"

# =============================================================================
# WORKFLOW METHOD
# Set to your team's methodology
# =============================================================================

method: cycles   # Options: cycles | sprints | kanban | custom

# =============================================================================
# METHOD DEFINITIONS
# Rules and terminology for each methodology
# =============================================================================

methods:

  # ---------------------------------------------------------------------------
  # CYCLES (Linear Method)
  # ---------------------------------------------------------------------------
  cycles:
    description: "Linear Method — fixed timeboxes, flexible scope"
    duration: 2_weeks
    philosophy: |
      Cycles are fixed time periods where scope flexes.
      We don't estimate, we scope to fit.
      Progress is tracked via hill charts, not burndowns.

    rules:
      no_backlogs:
        description: "We do not maintain backlogs. Ideas go to Triage."
        violation: "Creating a Backlog view"
        response: "REFUSE. Explain: We use Triage, not Backlogs."
        severity: error

      no_story_points:
        description: "We do not estimate in points. We scope by cycle fit."
        violation: "Adding story point field"
        response: "REFUSE. Explain: Scope to fit cycle, don't estimate."
        severity: error

      hill_charts:
        description: "We track progress via hill charts, not burndowns."
        violation: "Creating burndown chart"
        response: "SUGGEST. Offer: Use hill chart instead."
        severity: warning

      triage_inbox:
        description: "New issues go to Triage, not directly to cycle."
        violation: "Creating issue in active cycle"
        response: "WARN. Ask: Should this be triaged first?"
        severity: warning

      cooldown:
        description: "2-week cooldown between cycles for cleanup and planning."
        violation: "Scheduling back-to-back cycles"
        response: "WARN. Ask: Have you planned for cooldown?"
        severity: warning

    terminology:
      sprint: cycle
      backlog: triage
      story_points: scope
      burndown: hill_chart
      velocity: throughput
      standup: sync
      retrospective: cooldown_review

  # ---------------------------------------------------------------------------
  # SPRINTS (Scrum)
  # ---------------------------------------------------------------------------
  sprints:
    description: "Scrum — fixed scope, fixed time"
    duration: 2_weeks
    philosophy: |
      Sprints commit to specific scope within a timebox.
      Velocity helps predict future capacity.
      Burndown tracks progress against commitment.

    rules:
      backlog_required:
        description: "Sprint backlog must exist."
        violation: "No backlog for sprint"
        response: "WARN. Ask: Where is the sprint backlog?"
        severity: warning

      story_points:
        description: "Stories should be estimated."
        violation: "Unestimated story in sprint"
        response: "WARN. Ask: What's the estimate?"
        severity: warning

      sprint_goal:
        description: "Each sprint should have a clear goal."
        violation: "Sprint without defined goal"
        response: "WARN. Ask: What's the sprint goal?"
        severity: warning

    terminology:
      cycle: sprint
      triage: backlog
      scope: story_points
      hill_chart: burndown
      throughput: velocity
      sync: standup
      cooldown_review: retrospective

  # ---------------------------------------------------------------------------
  # KANBAN
  # ---------------------------------------------------------------------------
  kanban:
    description: "Continuous flow — no timeboxes"
    duration: null   # No fixed duration
    philosophy: |
      Work flows continuously without artificial timeboxes.
      WIP limits ensure focus and prevent overload.
      Lead time and cycle time are key metrics.

    rules:
      wip_limits:
        description: "Work in progress limits must be respected."
        violation: "Exceeding WIP limit"
        response: "BLOCK. Explain: Complete something before starting new."
        severity: error

      no_deadlines:
        description: "Kanban doesn't have sprint deadlines."
        violation: "Setting sprint deadline"
        response: "WARN. Explain: Use cycle time, not deadlines."
        severity: warning

      pull_not_push:
        description: "Work is pulled when capacity available, not pushed."
        violation: "Assigning work to overloaded queue"
        response: "WARN. Explain: Pull when ready, don't push."
        severity: warning

    terminology:
      sprint: swimlane
      backlog: queue
      velocity: cycle_time
      burndown: cumulative_flow

# =============================================================================
# AGENT BEHAVIOR
# How the agent enforces workflow rules
# =============================================================================

agent_behavior:

  # Replace violating terminology in prompts
  terminology_replacement: true

  # Refuse to generate workflow-violating views
  refuse_violations: true

  # Suggest alternatives when refusing
  suggest_alternatives: true

  # Response templates
  responses:
    refuse: |
      I can't create a {violation}.

      Your workflow is configured as "{method}":
        - {old_term} → {new_term}

      Would you like me to create a {alternative} instead?

      [Yes, {alternative}] [Override Workflow] [Cancel]

    warn: |
      Note: This might conflict with your "{method}" workflow.
      {explanation}

      Continue anyway? [Y/n]

    block: |
      This action violates your workflow rules.

      Violation: {violation}
      Rule: {rule}

      This is a hard constraint. Please adjust your request.

# =============================================================================
# GOVERNANCE INTEGRATION
# Tracking and amendment of workflow rules
# =============================================================================

governance:

  # Log workflow violations
  log_violations: true
  log_path: grimoires/sigil/state/workflow-violations.log

  # Allow overrides with justification
  override_allowed: true
  override_requires_justification: true

  # Amendment protocol for workflow changes
  amendment_allowed: true

  # Format for violation log
  log_format: |
    [{timestamp}] {severity}
      Method: {method}
      Violation: {violation}
      Rule: {rule}
      Action: {action_taken}
      Justification: {justification}
      Author: {author}

# =============================================================================
# WORKFLOW CALENDAR
# Optional: Define your cycle/sprint schedule
# =============================================================================

calendar:
  # Example configuration (customize for your team)
  current_cycle: null
  cycle_start_day: monday
  sync_days: [monday, wednesday, friday]
  cooldown_activities:
    - technical_debt
    - documentation
    - exploration
    - planning_next_cycle
