name: unlocking-decisions
description: Unlock a decision early with Taste Owner approval
version: "3.0.0"

triggers: []  # Internal skill, not user-invoked

examples:
  - input: "Unlock decision DEC-2026-001"
    description: "Unlock a decision before its natural unlock date"

inputs:
  - name: decision_id
    type: string
    required: true
    description: Decision ID to unlock

  - name: reason
    type: string
    required: true
    description: Reason for early unlock

  - name: approved_by
    type: string
    required: true
    description: Taste Owner who approved the unlock

outputs: []  # Updates decision file in place

internal: true
