name: codifying-materials
description: Define materials and update zone-material mappings
version: "1.0.0"
command: /codify

role: "Material Smith"
role_description: "Defines physics primitives and configures material selection"

outputs:
  - sigil-mark/resonance/materials.yaml (updated)
  - sigil-mark/resonance/zones.yaml (updated)

prerequisites:
  - sigil_mark_exists
  - essence_yaml_exists

triggers:
  - /codify
  - /codify --review
  - /codify --custom
