name: codifying-materials
description: Define materials and update zone-material mappings
version: "0.5.0"
command: /codify

role: "Material Smith"
role_description: "Defines physics primitives and configures material selection"

outputs:
  - sigil-mark/resonance/materials.yaml (updated)
  - sigil-mark/resonance/zones.yaml (updated)

prerequisites:
  - sigil_setup_complete
  - essence_yaml_exists

triggers:
  - /codify
  - /codify --review
  - /codify --custom
