/**
 * Sigil Soul Engine v10
 * 
 * A design context framework for AI-assisted product development.
 * "The best products feel like they were crafted by a human,
 *  even when generated by a machine."
 */

// Material Core
export {
  MaterialType,
  MaterialPhysics,
  getMaterial,
  detectMaterial,
  GlassMaterial,
  ClayMaterial,
  MachineryMaterial,
} from './material/MaterialCore';

// Material Components
export {
  MaterialProvider,
  useMaterial,
  MaterialButton,
  MaterialCard,
  MaterialInput,
  ServerTickButton,
  CommandPalette,
} from './material/MaterialComponents';

// Sync / Interaction Router
export {
  SyncStrategy,
  SyncConfig,
  InteractionRouter,
  interactionRouter,
  detectSyncStrategy,
} from './sync/InteractionRouter';

// Sync Hooks
export {
  useLocalFirst,
  useServerTick,
  useCRDTText,
  useLocalOnly,
  selectSyncHook,
} from './hooks/useSyncHooks';

// Tension System
export {
  TensionState,
  DEFAULT_TENSIONS,
  TENSION_PRESETS,
  tensionsToCSSVariables,
  TensionProvider,
  useTensions,
  TensionSlider,
  TensionControlsPanel,
} from './workbench/TensionSystem';
