name: proving-features
description: Register a feature for proving period with domain-specific monitors
version: "3.0.0"

triggers:
  - "/prove"

examples:
  - input: "/prove"
    description: "Start proving interview for a feature"
  - input: "/prove token-swap"
    description: "Register token-swap feature for proving"
  - input: "/prove onboarding --domain creative"
    description: "Prove feature with specific domain monitors"

inputs:
  - name: feature
    type: string
    required: false
    description: Feature name to register for proving

  - name: domain
    type: string
    required: false
    description: Domain for monitor selection (defi, creative, community, games)

outputs:
  - path: sigil-mark/proving-grounds/active/{feature}.yaml
    description: Proving status record with monitors and tracking
