name: initializing-sigil
description: Initialize Sigil v4 Design Physics Engine on a repository
version: "0.5.0"

triggers:
  - "/sigil-setup"

examples:
  - input: "/sigil-setup"
    description: "Initialize Sigil v4 on current repo"

inputs: []

outputs:
  # Core state zone
  - path: sigil-mark/core/sync.yaml
    description: Temporal Governor (tick modes, sync authority)
  - path: sigil-mark/core/budgets.yaml
    description: Cognitive, visual, complexity budgets
  - path: sigil-mark/core/fidelity.yaml
    description: Fidelity Ceiling (Mod Ghost Rule)
  - path: sigil-mark/core/lens.yaml
    description: Lens Registry (rendering layers)

  # Resonance layer
  - path: sigil-mark/resonance/materials.yaml
    description: Clay, Machinery, Glass physics
  - path: sigil-mark/resonance/zones.yaml
    description: Path-based zone definitions
  - path: sigil-mark/resonance/tensions.yaml
    description: Tuning sliders (playfulness, weight, density, speed)
  - path: sigil-mark/resonance/essence.yaml
    description: Product soul (populated by /envision)

  # Memory layer
  - path: sigil-mark/memory/eras/era-1.yaml
    description: Era versioning template
  - path: sigil-mark/memory/decisions/
    description: Decision records
  - path: sigil-mark/memory/mutations/active/
    description: Active mutations
  - path: sigil-mark/memory/graveyard/
    description: Deprecated decisions

  # Taste Key
  - path: sigil-mark/taste-key/holder.yaml
    description: Taste Key authority definition
  - path: sigil-mark/taste-key/rulings/
    description: Taste Key rulings directory

  # Configuration
  - path: .sigilrc.yaml
    description: Framework configuration
  - path: .sigil-setup-complete
    description: Setup completion marker
  - path: .sigil-version.json
    description: Version tracking
