# Sigil Configuration
# v5.9 "The Lucid Studio"

sigil: "5.9.0"

# Zone Definitions
# Map file paths to physics zones
zones:
  
  critical:
    paths:
      - "src/features/checkout/**"
      - "src/features/claim/**"
      - "src/features/vault/**"
      - "src/features/transfer/**"
    default_physics: server-tick
    data_types:
      - Money
      - Balance
      - Transfer
    persona_overrides:
      newcomer:
        timing_modifier: 1.5    # Slower for newcomers
        show_confirmation: true
      power_user:
        timing_modifier: 0.8    # Faster for power users
        
  standard:
    paths:
      - "src/features/**"
    default_physics: crdt
    data_types:
      - Task
      - Document
      - Comment
      
  admin:
    paths:
      - "src/admin/**"
      - "src/features/settings/**"
    default_physics: local-first
    data_types:
      - Preference
      - Toggle
      - Filter

# Workflow Configuration
workflow:
  method: cycles
  duration: 2_weeks
  
  forbidden:
    - sprint
    - backlog
    - story_points
    - burndown
    
  terminology:
    sprint: cycle
    backlog: triage
    story_points: scope
    burndown: hill_chart

# Governance Configuration
governance:
  
  # Status propagation behavior
  contagion: propagate  # 'propagate' | 'block' | 'warn'
  
  # Justification requirements
  justification_required: true
  
  # Amendment protocol
  amendment_protocol: true
  
  # Override tracking
  track_overrides: true
  log_path: sigil-mark/governance/justifications.log

# ESLint Integration
eslint:
  enabled: true
  rules:
    enforce-tokens: error
    zone-compliance: warn
    input-physics: warn
    data-physics: error

# Remote Soul (Optional)
# Uncomment to enable A/B testing of vibes
# remote_soul:
#   provider: launchdarkly
#   key: sigil-vibes
#   timeout_ms: 100
#   fallback_to_local: true
