# Sigil Configuration
# Root configuration - inherited by all zones

sigil: "1.2.4"

# Default recipe set (override in zone-specific configs)
recipes: machinery

# Default sync mode
sync: client_authoritative

# PR-native refinement configuration
refinement:
  sources:
    - vercel_preview_comments
    - github_pr_comments
    - linear_issue_comments
  auto_commit: true
  commit_prefix: "refine"

# Workbench configuration
workbench:
  browser:
    provider: claude-mcp
    url: http://localhost:3000
  compare:
    enabled: true
    history: 5
    toggle_key: space

# Global constraints (apply everywhere)
constraints:
  # These can never be overridden
  impossible:
    - "optimistic_ui in server_authoritative zone"
    - "raw physics outside sandbox"
  
  # These require explicit override
  block:
    - "loading_spinners in decisive zone"

# Component detection paths
component_paths:
  - "src/components/"
  - "src/features/**/components/"
  - "app/components/"
  - "components/"
