name: sigil-updating
description: Pull latest Sigil framework and refresh symlinks
version: "2.0.0"

triggers:
  - "/update"

examples:
  - input: "/update"
    description: "Pull latest and refresh symlinks"
  - input: "/update --check"
    description: "Preview updates without applying"
  - input: "/update --force"
    description: "Force refresh even if current"

inputs:
  - name: check
    type: flag
    description: Preview updates without applying
  - name: force
    type: flag
    description: Force refresh even if current

outputs:
  - path: .sigil-version.json
    description: Updated version manifest
