name: locking-decisions
description: Lock a decision after outcome is recorded
version: "3.0.0"

triggers: []  # Internal skill, not user-invoked

examples:
  - input: "Lock decision DEC-2026-001"
    description: "Lock a decision after it has been decided"

inputs:
  - name: decision_id
    type: string
    required: true
    description: Decision ID to lock

  - name: lock_duration_days
    type: number
    required: false
    description: Days until unlock (defaults to config-based duration)

outputs: []  # Updates decision file in place

internal: true
