name: crafting-guidance
description: Provide design guidance with value/flaw awareness during implementation
version: "3.0.0"

triggers:
  - "/craft"

examples:
  - input: "/craft"
    description: "Get general design guidance"
  - input: "/craft src/components/Button.tsx"
    description: "Get zone-specific guidance for a file"
  - input: "/craft \"How should modals animate?\""
    description: "Ask a design question"

inputs:
  - name: context
    type: string
    required: false
    description: File path or design question

outputs: []

checks:
  - path: sigil-mark/soul-binder/immutable-values.yaml
    description: Check for value violations
  - path: sigil-mark/soul-binder/canon-of-flaws.yaml
    description: Check for protected flaw impacts
