/**
 * Claude Context Generation
 *
 * Generates CLAUDE.md content for AI context injection.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { parse } from 'yaml';
import type { SigilConfig } from './config.js';
import { MATERIALS } from '../material/index.js';

interface Correction {
  id: string;
  issue: string;
  correction: string;
  applies_to?: string;
}

/**
 * Load corrections from YAML file
 */
function loadCorrections(correctionsPath: string): Correction[] {
  if (!existsSync(correctionsPath)) return [];

  try {
    const content = readFileSync(correctionsPath, 'utf-8');
    const data = parse(content) as { corrections?: Correction[] };
    return data.corrections || [];
  } catch {
    return [];
  }
}

/**
 * Generate CLAUDE.md content
 */
export function generateClaudeContext(config: SigilConfig): string {
  const tensions = config.tensions.current || {
    playfulness: 50,
    weight: 50,
    density: 50,
    speed: 50,
  };

  // Try to load corrections
  const correctionsPath = join(process.cwd(), '.sigil', 'corrections.yaml');
  const corrections = loadCorrections(correctionsPath);

  // Determine active material (most common in zones or default)
  const materialCounts: Record<string, number> = { glass: 0, clay: 0, machinery: 0 };
  for (const zone of config.zones) {
    materialCounts[zone.material]++;
  }
  const activeMaterial = Object.entries(materialCounts).sort(
    (a, b) => b[1] - a[1]
  )[0][0];

  return `# Sigil Soul Engine Context

This project uses Sigil v0.4 Soul Engine for design context.

## Material Physics

Active Material: **${activeMaterial.charAt(0).toUpperCase() + activeMaterial.slice(1)}** (${MATERIALS[activeMaterial as keyof typeof MATERIALS]})

Materials define physics, not just styles:
- **Glass**: Light, translucent. Blur, refraction. For exploratory zones.
- **Clay**: Warm, tactile. Soft shadows, spring motion. For critical zones.
- **Machinery**: Instant, precise. Zero transitions. For command palettes.

## Current Tensions

| Axis | Value | Effect |
|------|-------|--------|
| Playfulness | ${tensions.playfulness} | ${tensions.playfulness > 60 ? 'Rounded curves, vibrant colors' : tensions.playfulness < 40 ? 'Sharp edges, muted colors' : 'Balanced curves and color'} |
| Weight | ${tensions.weight} | ${tensions.weight > 60 ? 'Prominent shadows, bold fonts' : tensions.weight < 40 ? 'Light shadows, thin fonts' : 'Moderate shadows and fonts'} |
| Density | ${tensions.density} | ${tensions.density > 60 ? 'Compact layout, smaller text' : tensions.density < 40 ? 'Spacious layout, larger text' : 'Balanced spacing'} |
| Speed | ${tensions.speed} | ${tensions.speed > 60 ? 'Quick transitions (< 150ms)' : tensions.speed < 40 ? 'Deliberate transitions (> 250ms)' : 'Moderate transitions'} |

## Zone Configuration

${config.zones.map((z) => `- \`${z.name}\` → ${z.material.charAt(0).toUpperCase() + z.material.slice(1)} + ${z.sync}: ${z.paths.join(', ')}`).join('\n')}

## Sync Strategy Rules

| Strategy | When | UI Rule |
|----------|------|---------|
| Server-Tick | Money, health, inventory | MUST show pending state |
| LWW | Preferences, toggles | Optimistic OK |
| CRDT | Text, comments | Show presence |

**CRITICAL**: Never use optimistic UI for server-tick data.

## Local Corrections

${corrections.length > 0 ? corrections.map((c) => `- ${c.issue}: ${c.correction}`).join('\n') : '_No corrections recorded yet._'}

## Commands

- \`/craft\` — Get design guidance with material + tension context
- \`/garden\` — Show paper cut analysis
- \`/approve\` — Human sign-off on patterns

---

*Generated by Sigil Soul Engine v0.4*
`;
}
