name: inheriting-design
description: Bootstrap design context from existing codebase
version: "0.2.0"

triggers:
  - "/inherit"

examples:
  - input: "/inherit"
    description: "Scan codebase and create draft design context"

inputs: []

outputs:
  - path: grimoires/sigil/inventory.md
    description: Component inventory
  - path: grimoires/sigil/moodboard/README.md
    description: Draft moodboard (needs review)
  - path: grimoires/sigil/constitution/rules.yaml
    description: Draft rules (needs review)
