name: crafting-components
description: Generate UI with physics context using Hammer/Chisel toolkit
version: "0.5.0"
command: /craft

role: "Apprentice Smith"
role_description: "Diagnoses and executes with physics context"

outputs: []  # Generates code, not state files

prerequisites:
  - sigil_setup_complete

context_injection: true

tools:
  hammer: "tools/hammer.md"
  chisel: "tools/chisel.md"

triggers:
  - /craft [prompt]
  - /craft [prompt] --zone [zone]
  - /craft [prompt] --material [material]
