name: crafting-components
description: Generate UI components using zone-appropriate recipes (Sigil v1.2.4)
version: "1.2.4"
command: /craft

role: "Apprentice Smith"
role_description: "Generates components using recipes. No raw physics outside sandbox."

outputs: []  # Generates code, not state files

reads:
  # Zone config
  - .sigilrc.yaml
  - src/**/.sigilrc.yaml
  # Recipes
  - sigil-mark/recipes/decisive/*.tsx
  - sigil-mark/recipes/machinery/*.tsx
  - sigil-mark/recipes/glass/*.tsx
  # Core
  - sigil-mark/core/zone-resolver.ts
  - sigil-mark/hooks/useServerTick.ts

prerequisites:
  - sigil_mark_exists

context_injection: true

triggers:
  - /craft [description]
  - /craft [description] --file [path]
  - /craft [description] --zone [zone]
