name: observing-feedback
description: Visual feedback loop - capture screenshots and analyze against design rules
version: "4.1.0"

triggers:
  - "/observe"

examples:
  - input: "/observe"
    description: "Capture current screen and analyze against rules"
  - input: "/observe --component ClaimButton"
    description: "Focus analysis on a specific component"
  - input: "/observe --screenshot path/to/screenshot.png --rules"
    description: "Analyze existing screenshot against full rules"
  - input: "/observe --url http://localhost:3000/claim"
    description: "Navigate to URL and analyze"

inputs:
  - name: component
    type: string
    required: false
    description: Focus analysis on a specific component
  - name: screenshot
    type: string
    required: false
    description: Path to existing screenshot file
  - name: rules
    type: boolean
    required: false
    description: Include full rules analysis (more detailed output)
  - name: url
    type: string
    required: false
    description: URL to navigate to before capturing

outputs:
  - path: .sigil-observations/feedback/*.md
    description: Feedback report with questions and recommendations

checks:
  - path: grimoires/sigil/constitution/constitution.yaml
    description: Load design constitution for analysis
  - path: grimoires/sigil/moodboard/README.md
    description: Load moodboard for feel comparison
  - path: .sigilrc.yaml
    description: Load zone definitions
