name: lore
description: Slot external knowledge into Rune constructs
user-invocable: true
disable-model-invocation: true

allowed-tools:
  - Read
  - Write
  - Glob
  - Bash

triggers:
  commands:
    - lore
  keywords:
    - reference
    - external
    - knowledge
    - slot

zones:
  system:
    path: .claude
    permission: read-write
  references:
    path: .claude/references
    permission: read-write
