name: validating-lenses
description: Validate asset across all lenses, prioritizing most constrained
version: "3.0.0"

triggers: []  # Internal skill, not user-invoked

examples:
  - input: "Validate component for all lenses"
    description: "Check component meets constraints for power_user, mobile, accessibility"

inputs:
  - name: file_path
    type: string
    required: true
    description: File path to validate

  - name: lens_ids
    type: array
    required: false
    description: Specific lenses to validate against (defaults to all)

outputs: []  # Returns validation results to calling skill

internal: true
