# Sigil Workflow Engine
# Process is soul. Wrong method = wrong product.
# Based on Linear Method principles

version: "5.9.0"

# Workflow Method
# Set to your team's methodology
method: cycles  # Options: cycles | sprints | kanban | custom

# Method Definitions
methods:
  
  cycles:
    description: "Linear Method — fixed timeboxes, flexible scope"
    duration: 2_weeks
    rules:
      no_backlogs:
        description: "We do not maintain backlogs. Ideas go to Triage."
        violation: "Creating a Backlog view"
        response: "REFUSE. Explain: We use Triage, not Backlogs."
        
      no_story_points:
        description: "We do not estimate in points. We scope by cycle fit."
        violation: "Adding story point field"
        response: "REFUSE. Explain: Scope to fit cycle, don't estimate."
        
      hill_charts:
        description: "We track progress via hill charts, not burndowns."
        violation: "Creating burndown chart"
        response: "SUGGEST. Offer: Use hill chart instead."
        
      triage_inbox:
        description: "New issues go to Triage, not directly to cycle."
        violation: "Creating issue in active cycle"
        response: "WARN. Ask: Should this be triaged first?"
        
    terminology:
      sprint: cycle
      backlog: triage
      story_points: scope
      burndown: hill_chart
      velocity: throughput
      
  sprints:
    description: "Scrum — fixed scope, fixed time"
    duration: 2_weeks
    rules:
      backlog_required:
        description: "Sprint backlog must exist."
        violation: "No backlog for sprint"
        response: "WARN. Ask: Where is the sprint backlog?"
        
      story_points:
        description: "Stories should be estimated."
        violation: "Unestimated story in sprint"
        response: "WARN. Ask: What's the estimate?"
        
    terminology:
      cycle: sprint
      triage: backlog
      scope: story_points
      hill_chart: burndown
      throughput: velocity
      
  kanban:
    description: "Continuous flow — no timeboxes"
    rules:
      wip_limits:
        description: "Work in progress limits must be respected."
        violation: "Exceeding WIP limit"
        response: "BLOCK. Explain: Complete something before starting new."
        
      no_deadlines:
        description: "Kanban doesn't have sprint deadlines."
        violation: "Setting sprint deadline"
        response: "WARN. Explain: Use cycle time, not deadlines."
        
    terminology:
      sprint: swimlane
      backlog: queue
      velocity: cycle_time

# Agent Behavior
agent_behavior:
  
  # Replace violating terminology in prompts
  terminology_replacement: true
  
  # Refuse to generate workflow-violating views
  refuse_violations: true
  
  # Suggest alternatives when refusing
  suggest_alternatives: true
  
  # Example responses
  responses:
    refuse: |
      I can't create a {violation}.
      
      Your workflow is configured as "{method}":
        - {old_term} → {new_term}
      
      Would you like me to create a {alternative} instead?
      
    warn: |
      Note: This might conflict with your "{method}" workflow.
      {explanation}
      
      Continue anyway? [Y/n]

# Governance Integration
governance:
  
  # Log workflow violations
  log_violations: true
  log_path: sigil-mark/governance/workflow-violations.log
  
  # Allow overrides with justification
  override_allowed: true
  override_requires_justification: true
  
  # Amendment protocol for workflow changes
  amendment_allowed: true
