name: crafting-components
version: "1.0.0"
description: |
  Generate and refine UI components within Sigil's physics constraints.
  Uses Hammer (diagnose) and Chisel (execute) tools.

triggers:
  - /craft

outputs:
  - type: code
    description: Generated or modified component code
  - type: handoff
    description: Loa handoff context (if structural issue)

dependencies:
  - core/sync.yaml
  - core/budgets.yaml
  - core/fidelity.yaml
  - resonance/zones.yaml
  - resonance/materials.yaml
  - resonance/tensions.yaml
